### ISSUE TITLE
Change the text structure

### ISSUE THREAD

**Issue by Szymanpaulina** [CodeForPoznan/startbootstrap-freelancer#5]
To move the letter "i" from 2nd line to 3rd line (to start new line with "i")

Grupą osób, która uważa, że warto
ulepszać świat za pomocą technologii "i"
chce dostarczyć narzędzia, dzięki którym
każdy będzie mógł to robić.

**Comment by w1stler** [comment]
I would change it within the PR, that added this text. Solution: add non-breaking space `;nbsp;`
